name: pdf_brain
description: "A smart offline PDF summarizer with a clean UI."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  syncfusion_flutter_pdf: ^24.1.41
  file_picker: ^10.2.0
  path_provider: ^2.1.5
  share_plus: ^11.0.0
  google_fonts: ^6.2.1
  flutter_tts: ^4.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.3.10

flutter:
  uses-material-design: true

  assets:
    - assets/icon.png
    - assets/icons/brain_icon.png

flutter_icons:
  android: true
  ios: true
  image_path: assets/icon.png

flutter_native_splash:
  color: "#ffffff"
  image: assets/icon.png
  android: true
  ios: true
  web: false
  android_gravity: center
  ios_content_mode: center
  fullscreen: true
  color_dark: "#121212"
  image_dark: assets/icon.png
